### ISSUE TITLE
Remove support Laravel 5.5 in documents

### ISSUE THREAD

**Issue by oanhnn** [hamburgscleanest/laravel-guzzle-throttle#1]
Remove support Laravel 5.5 in documents

## Detailed description

In `composer.json` file:

```
"require": {
    "php": ">=7.1.0",
    "hamburgscleanest/guzzle-advanced-throttle": "1.*",
    "illuminate/support": "5.6.*"
  },
```
This package required `"illuminate/support": "5.6.*"`, it only available in Laravel `5.6.*`
But in this package's README, it have configure for Laravel < 5.5

I think you should update README

**Comment by Chroma91** [comment]
I'm using it with a 5.5 installation of Laravel and it's working. But I'll have a look again and also check a Laravel 5.4 installation. Afterwards I will update the README if needed.

Thanks for pointing it out!

**Comment by Chroma91** [comment]
I think it was some kind of a caching issue. After a clean installation of the composer dependencies it doesn't work anymore. So I'll update the README, thanks!
