### ISSUE TITLE
Locked to PHP version >= 7.1.0

### ISSUE THREAD

**Issue by jofomah** [hamburgscleanest/laravel-guzzle-throttle#2]
Packages is locked toPHP  version >= 7.1.0

## Currently cannot install this package on PHP 7.0.23

Provide a detailed description of the change or addition you are proposing.

Make it clear if the issue is a bug, an enhancement or just a question.

## Context

Me because i want to support  >= 7.0

How can it benefit other users?

Others who who also want to support >= won't be able to use this package.

## Possible implementation

Is there any specific reason why this is locked to >= 7.1.0, if none, then maybe lower to 7.0

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used: PHP 7.0.23:
* Operating system and version: Ubuntu 16

**Comment by Chroma91** [comment]
I didn't test it on lower PHP versions yet.
I'm open for a PR which sets the minimum version to "7.0" and slo adds PHP 7.0 to the `.travis.yml`.
If all the testes pass, we can merge it! 👍

**Comment by Chroma91** [comment]
We are using PHP 7.1 features at least in guzzle-advanced-throttle, so unfortunately I cannot officially support PHP 7.0.

I recommend you to either fork the package and replace the 7.1 features or upgrade to PHP 7.1.
The tests are convering every important case, if all of them pass after your changes, it'll be fine.

Sorry about that. Feel free to reopen the ticket when there are questions :)
