### ISSUE TITLE
funnel

### ISSUE THREAD

**Issue by tarekadam** [hamburgscleanest/laravel-guzzle-throttle#39]
Hey, nice work.  I made something similar recently.  My throttle is fine, but I've got issues with funnel.  It works fine in homestead but not in my vapor deploy.  Something about "All keys do not map to the same slot" from redis cluster.  Have you taken a crack at funnel?

**Comment by Chroma91** [comment]
Hey, thanks! I haven't used the funnel method yet, sorry :/ I'm not sure if I'm able to help.

However, maybe I can help you if you have more error details. Some implementation details might help as well.

**Comment by shoemoney** [comment]
> Hey, nice work. I made something similar recently. My throttle is fine, but I've got issues with funnel. It works fine in homestead but not in my vapor deploy. Something about "All keys do not map to the same slot" from redis cluster. Have you taken a crack at funnel?

Did you ever get this figured out?   I am getting the same error.   I am pretty sure it is related to the way vapor calls the redis cache but havent figured it out yet.

**Comment by Eklado** [comment]
I know this is an extremely late reply but I'll answer in case someone find this thread like I did.

Redis Cluster uses hashtags for its key so all you need to do is to make the funnel key between {hashtags} (which is curly brackets) as follows:

`Redis::funnel('{' . $key . '}')->limit(5)->then(function () {
}, function () {
            return $this->release(rand(1, 5));
        });`
